### PR TITLE
Issue #22

### PR DESCRIPTION
**Pull request by rendel**

### CODE REVIEW

**Comment by scampi** [comment]
looks good. I will test the branch with kibi.

**Comment by rendel** [comment]
ok thanks, I'll merge when your test will be successful.

**Comment by scampi** [comment]
README needs to be updated:

```
    Plugins can be installed from a custom URL or file location as follows:

        plugin install http://some.domain.name//my-plugin-1.0.0.zip
        plugin install file:/path/to/my-plugin-1.0.0.zip
```

`plugin-descriptor.properties` file missing: https://www.elastic.co/guide/en/elasticsearch/plugins/2.1/plugin-authors.html

**Comment by scampi** [comment]
nit-pick: in the README, we should say that for version 1.0, the plugin name is "FilterJoinPlugin".

**Comment by scampi** [comment]
the example in README needs to be updated I think.

**Comment by rendel** [comment]
what's the problem with the example ? it does not work ?

**Pull request merged**
