### PR TITLE
dev up to ES 2.4.0 + Lucene 5.5.2

### PR DESCRIPTION
**Pull request by lmangani**
PR for new Dev Branch 2.4.0

### CODE REVIEW

**Comment by turp1twin** [comment]
Any reason this PR hasn't been merged yet?

**Comment by rendel** [comment]
No apart from other priorities, I'll try to look at this during the week.

**Comment by turp1twin** [comment]
Thanks Renaud, definitely would be appreciated. Cheers!

Jeff

**Comment by ajrasch** [comment]
Would really like to have this...any thoughts on a release? Thanks!!

**Comment by tomasfalt** [comment]
Me too! Any time soon?

**Comment by rendel** [comment]
Thanks for the patch, 
for the future, could you please ensure to make pull request against the `develop` branch. Thanks!

**Comment by lmangani** [comment]
@rendel ACK

**Pull request merged**
